### ISSUE TITLE
[BUG]: Karavi Observability documentation does not describe the coupling/requirement with the CSI PowerFlex driver

### ISSUE THREAD

**Issue by gallacher** [dell/karavi#9]
**Describe the bug**
The Karavi Observability documentation does not indicate the relationship/coupling between the CSI PowerFlex driver and the Metrics for PowerFlex service.  The documentation also does not indicate that the CSI PowerFlex driver is required.

**To Reproduce**
N/A

**Expected behavior**
The Karavi Observability documentation contains a description of how the Metrics for PowerFlex service ties in with the CSI PowerFlex driver.  The documentation also describes that the CSI PowerFlex driver is required and the specific version(s) that are required.

**Screenshots**
N/A

**Logs**
N/A

**System Information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ioeicicdsvc** [comment]
link: 1689
